
NODES = {
    "docker01" => {
        "cpus" => 1,
        "memory" => 2048,
        "ip" => "192.168.56.101",
    },
    "docker02" => {
        "cpus" => 1,
        "memory" => 2048,
        "ip" => "192.168.56.102",
    },
    "docker03" => {
        "cpus" => 1,
        "memory" => 2048,
        "ip" => "192.168.56.103",
    }
}

Vagrant.configure("2") do |config|
    start_ip = 11
    NODES.each do |(name, params)|
        config.vm.define "#{name}" do |c|
            c.vm.box = "ubuntu/focal64"
            c.vm.hostname = "#{name}"
            c.vm.network "private_network", ip: "#{params['ip']}", netmask: "255.255.255.0", name: "vboxnet0"
            c.vm.disk :disk, size: "50GB", primary: true
            c.vm.provider "virtualbox" do |vb|
                vb.memory = params['memory']
                vb.cpus = params['cpus']
                vb.customize ["modifyvm", :id, "--audiocontroller", "sb16"]
            end
        end
    end
end